version: "3"

services: 
    web:
        container_name: web
        build: web/
        ports:
            - "8080:80"
        debends_on:
            - mongodb
            - gnuplot-service

    mongodb:
        container_name: mongodb
        image: mongo
    volumes:
            - database:/data/db

    gnuplot-service:
        container_name: gnuplot-service
        build: gnuplot-service/
    volumes: 
            db:
                external: 
                    name: database